### ISSUE TITLE
Spectators affected by thirst

### ISSUE THREAD

**Issue by RedStoner** [Hellkitty/essentialnourishment#3]
While in gamemode 3 (spectator), you are effected by thirst. However, you are unable to consume anything in this mode. Quite the annoying issue.

**Comment by Hellkitty** [comment]
Sorry. I have been in the hospital for a few days and I have not seen my emails or notifications. I will address this issue tommorow

**Comment by Hellkitty** [comment]
This was fixed by https://github.com/Hellkitty/essentialnourishment/commit/3a0a5d2cf9accae60388c5c455c4af38d1fff67f

**Comment by RedStoner** [comment]
When should i be expecting to see this released?

**Comment by Hellkitty** [comment]
"Essential Nourishment 1.1.2" and a corresponding update "Positron 1.3" should be updated later today

**Comment by Hellkitty** [comment]
This was fixed by update 1.1.2.1 and a subsequential update positron 1.3
